title: Sahul Baig
#logo: /assets/img/headshot_circle.png
description: Iâ€™m a 3rd-year Computer Engineering student at TMU, passionate about software development, embedded systems, and microcontroller projects.
show_downloads: false
theme: jekyll-theme-minimal
